export const DELETE_TOPIC = 'DELETE_TOPIC';
export type DELETE_TOPIC = typeof DELETE_TOPIC;

export const OPEN_ADD_TOPIC_MODAL = 'OPEN_ADD_TOPIC_MODAL';
export type OPEN_ADD_TOPIC_MODAL = typeof OPEN_ADD_TOPIC_MODAL;

export const CLOSE_ADD_TOPIC_MODAL = 'CLOSE_ADD_TOPIC_MODAL';
export type CLOSE_ADD_TOPIC_MODAL = typeof CLOSE_ADD_TOPIC_MODAL;

export const OPEN_TASK_DETAIL_MODAL = 'OPEN_TASK_DETAIL_MODAL';
export type OPEN_TASK_DETAIL_MODAL = typeof OPEN_TASK_DETAIL_MODAL;

export const CLOSE_TASK_DETAIL_MODAL = 'CLOSE_TASK_DETAIL_MODAL';
export type CLOSE_TASK_DETAIL_MODAL = typeof CLOSE_TASK_DETAIL_MODAL;

export const ADD_TOPIC = 'ADD_TOPIC';
export type ADD_TOPIC = typeof ADD_TOPIC;

export const ADD_TASK = 'ADD_TASK';
export type ADD_TASK = typeof ADD_TASK;

export const DELETE_TASK = 'DELETE_TASK';
export type DELETE_TASK = typeof DELETE_TASK;

export const MOVE_TASK = 'MOVE_TASK';
export type MOVE_TASK = typeof MOVE_TASK;

export const UPDATE_TASK = 'UPDATE_TASK';
export type UPDATE_TASK = 'UPDATE_TASK';

export const MARK_TASK_DONE = 'MARK_TASK_DONE';
export type MARK_TASK_DONE = typeof MARK_TASK_DONE;

export const OPEN_ADD_TASK_MODAL = 'OPEN_ADD_TASK_MODAL';
export type OPEN_ADD_TASK_MODAL = typeof OPEN_ADD_TASK_MODAL;

export const CLOSE_ADD_TASK_MODAL = 'CLOSE_ADD_TASK_MODAL';
export type CLOSE_ADD_TASK_MODAL = typeof CLOSE_ADD_TASK_MODAL;

export const MARK_STEP_AS_DONE = 'MARK_STEP_AS_DONE';
export type MARK_STEP_AS_DONE = typeof MARK_STEP_AS_DONE;